# Docker Compose para Rails BaaS

services:
  # Aplicación Rails
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DATABASE_URL=postgresql://postgres:password@db:5432/rails_baas_development
      - SECRET_KEY_BASE=development_secret_key_for_docker
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      - db
    command: >
      bash -c "
        echo 'Esperando a PostgreSQL...' &&
        dockerize -wait tcp://db:5432 -timeout 60s &&
        echo 'PostgreSQL está listo!' &&
        echo 'Instalando gemas...' &&
        bundle install &&
        echo 'Configurando base de datos...' &&
        rails db:create 2>/dev/null || echo 'Base de datos ya existe' &&
        rails db:migrate &&
        rails db:seed &&
        echo 'Iniciando servidor Rails...' &&
        rails server -b 0.0.0.0 -p 3000
      "

  # Base de datos PostgreSQL
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: rails_baas_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  bundle_cache:
  postgres_data:
  redis_data:
